- IO: "Adios2StMan"
  Engine:
    Type: "BP5"
  Variables:
    - Variable: "map"
      Operations:
        - Type: mgard
          accuracy: 0.01
          lossless: Huffman_Zstd
          mode: REL
          s: 0
    - Variable: "COPY"
      Operations:
        - Type: mgard
          accuracy: 10.0
          lossless: Huffman_Zstd
          mode: ABS
          s: 0
    - Variable: "REAL"
      Operations:
        - Type: mgard
          accuracy: 10.0
          lossless: Huffman_Zstd
          mode: ABS
          s: 0
    - Variable: "IMAG"
      Operations:
        - Type: mgard
          accuracy: 10.0
          lossless: Huffman_Zstd
          mode: ABS
          s: 0
    - Variable: "COPY"
      Operations:
        - Type: mgard
          accuracy: 10.0
          lossless: Huffman_Zstd
          mode: ABS
          s: 0
    - Variable: "DATA"
      Operations:
        - Type: mgard
          accuracy: 10.0
          lossless: Huffman_Zstd
          mode: ABS
          s: 0
